version: '3'

services:
  db:
    container_name: 'db_psql'
    image: bitnami/postgresql:latest
    env_file:
      - ./.env
    ports:
      - 5432:5432
    volumes:
      - ./pgdata/:/bitnami/postgresql
  python_service:
    container_name: 'python_container'
    image: python:3.10
    volumes:
    - ./:/usr/application/teste/
    depends_on:
      - db
    tty: true
    stdin_open: true
    command: sh
    working_dir: /usr/application/teste

